spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/library
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
  liquibase:
    change-log: classpath:/changelog/changelog-master.xml
fvdf