spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/library
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
#  liquibase:
#    change-log: classspath:/changelog/db.changelog-master.xml
