spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/preferences
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false

  liquibase:
    change-log: classpath:/changelog/db.changelog-master.xml
