app:
  properties:
    daily-fee-rate: ${DAILY_FEE_RATE:0.5}
    fee-calculation-rate: ${FEE_RATE:0 30 7 * * *} # every day at 7.30
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/library
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #    open-in-view: false
    #    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:/changelog/changelog-master.xml
